[tasks.build-package]
script = '''
cd ./src
rm -f phytexia.sty
latex phytexia.ins
'''

[tasks.build-documentation]
script = '''
cd ./src
latexmk -pdflua phytexia.dtx -interaction=nonstopmode > phytexia.out-log
'''

[tasks.build-examples]
script = '''
rm -f examples/phytexia.sty
rm -f examples/json.lua
rm -f examples/phytexia.lua
rm -f examples/symbols
ln -rs src/phytexia.sty examples/phytexia.sty
ln -rs src/json.lua examples/json.lua
ln -rs src/phytexia.lua examples/phytexia.lua
ln -rs src/symbols/png-symbols/ examples/symbols
cd ./examples
latexmk -pdflua --shell-escape -interaction=nonstopmode main.tex > main.out-log
'''

[tasks.build-pngs]
script = '''
  cd ./src/symbols
  ./convert
'''

[tasks.build-tests]
dependencies = ["build-tests-prepare"]
script = '''
cd ./tests
latexmk -pdflua --shell-escape -interaction=nonstopmode cards.tex > cards.out-log
latexmk -pdflua --shell-escape -interaction=nonstopmode decks.tex > decks.out-log
latexmk -pdflua --shell-escape -interaction=nonstopmode symbols.tex > symbols.out-log
'''

[tasks.build-tests-prepare]
script = '''
rm -f tests/phytexia.sty
rm -f tests/json.lua
rm -f tests/phytexia.lua
rm -f tests/symbols
ln -rs src/phytexia.sty tests/phytexia.sty
ln -rs src/json.lua tests/json.lua
ln -rs src/phytexia.lua tests/phytexia.lua
ln -rs src/symbols/png-symbols/ tests/symbols
'''

[tasks.build-and-test-cards]
dependencies = ["build-tests-prepare", "build-package"]
script = '''
cd ./tests
latexmk -pdflua --shell-escape -interaction=nonstopmode cards.tex > cards.out-log
'''

[tasks.build-and-test-decks]
dependencies = ["build-tests-prepare", "build-package"]
script = '''
cd ./tests
latexmk -pdflua --shell-escape -interaction=nonstopmode decks.tex > decks.out-log
'''

[tasks.build-and-test-symbols]
dependencies = ["build-tests-prepare", "build-package"]
script = '''
cd ./tests
latexmk -pdflua --shell-escape -interaction=nonstopmode symbols.tex > symbols.out-log
'''

[tasks.clean-examples]
script = '''
cd ./examples
latexmk -c
rm -f *.ilg *.blg *.bak *.aux *.log *.toc *.out *.brf *.lox *.toe *.thm *.fdb_latexmk *.synctex.gz *.bbl *.gin *.fls *.idx *.ind *~ *.glo *.glg *.gls *.hd *.out-log
'''

[tasks.clean-tests]
script = '''
cd ./tests
latexmk -c
rm -f *.ilg *.blg *.bak *.aux *.log *.toc *.out *.brf *.lox *.toe *.thm *.fdb_latexmk *.synctex.gz *.bbl *.gin *.fls *.idx *.ind *~ *.glo *.glg *.gls *.hd *.out-log
'''

[tasks.clean-src]
script = '''
cd src
latexmk -c phytexia.dtx
rm -f *.ilg *.blg *.bak *.aux *.log *.toc *.out *.brf *.lox *.toe *.thm *.fdb_latexmk *.synctex.gz *.bbl *.gin *.fls *.idx *.ind *~ *.glo *.glg *.gls *.hd *.out-log
'''

[tasks.build-all]
run_task = { name = [
  "build-pngs",
  "build-package",
  "build-documentation",
  "build-examples",
],  fork = true}

[tasks.clean-all]
dependencies = [
  "clean-src",
  "clean-examples",
  "clean-tests",
]

[tasks.build-and-test]
run_task = { name = [
  "build-package",
  "build-tests",
],  fork = true}


[tasks.default]
#TODO
